/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.Interfaces;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import proyecto2.FuncionesTEMP;

/**
 *
 * @author Samantha
 */
public class Ventana3_1 extends javax.swing.JFrame {
    public static Ventana1 v1;
    private String NombreUser;
    /**
     * Creates new form Ventana3_1
     */
 /**
 * Constructor para crear una nueva ventana Ventana3_1.
 * Inicializa los componentes, establece la visibilidad de las ventanas y establece el manejador del evento de cierre de la ventana
     * @param v1 La ventana 1.
     * @param NombreUser El nombre del usuario.
     */
 
    public Ventana3_1(Ventana1 v1, String NombreUser) {
        initComponents();
        this.v1 =v1;
        this.NombreUser = NombreUser;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
         this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                FuncionesTEMP.WriteCSV(v1.ListaUsuarios); 
                
                System.exit(0);
            }
        });
    }

    public String getNombreUser() {
        return NombreUser;
    }

    public static Ventana1 getV1() {
        return v1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OPCcrearDoc = new javax.swing.JButton();
        OPCmyArea = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        FondoV3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione la opción que desea realizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        OPCcrearDoc.setBackground(new java.awt.Color(204, 204, 204));
        OPCcrearDoc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        OPCcrearDoc.setForeground(new java.awt.Color(0, 0, 0));
        OPCcrearDoc.setText("Crear nuevo documento");
        OPCcrearDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCcrearDocActionPerformed(evt);
            }
        });
        jPanel1.add(OPCcrearDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 170, 30));

        OPCmyArea.setBackground(new java.awt.Color(204, 204, 204));
        OPCmyArea.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        OPCmyArea.setForeground(new java.awt.Color(0, 0, 0));
        OPCmyArea.setText("Imprimir mis documentos");
        OPCmyArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCmyAreaActionPerformed(evt);
            }
        });
        jPanel1.add(OPCmyArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 163, 170, 30));

        inicio.setBackground(new java.awt.Color(204, 204, 204));
        inicio.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        inicio.setForeground(new java.awt.Color(0, 0, 0));
        inicio.setText("Atrás");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        jPanel1.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        cancelar.setBackground(new java.awt.Color(204, 204, 204));
        cancelar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 0));
        cancelar.setText("Cancelar Impresión");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, 30));

        FondoV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/FondoV3_11.png"))); // NOI18N
        jPanel1.add(FondoV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 *  Método que se ejecuta cuando se hace clic en el botón OPCcrearDoc.
 * Hace que la ventana actual sea invisible y muestra la ventana vent_CrearDoc.
 * @param evt El evento de clic en el botón.
 */
    private void OPCcrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCcrearDocActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vent_CrearDoc vent_CrearDoc= new Vent_CrearDoc  (this);
            
        vent_CrearDoc.setVisible(true);
    }//GEN-LAST:event_OPCcrearDocActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón 'inicio'.
 * Hace que la ventana actual sea invisible y muestra la ventana v1.
 * @param evt El evento de clic en el botón.
 */
    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_inicioActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón OPCmyArea.
 * Hace que la ventana actual sea invisible y muestra la ventana vent_myarea.
 * @param evt El evento de clic en el botón.
 */
    private void OPCmyAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCmyAreaActionPerformed
        this.setVisible(false);
        Vent_myArea vent_myarea = new Vent_myArea(this);
        vent_myarea.setVisible(true);
    }//GEN-LAST:event_OPCmyAreaActionPerformed
/**
 *  Método que se ejecuta cuando se hace clic en el botón 'cancelar'.
 * Hace que la ventana actual sea invisible y muestra la ventana cancelar.
 * @param evt El evento de clic en el botón. 
 */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vent_cancelar cancelar = new Vent_cancelar(this);
        cancelar.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoV3;
    private javax.swing.JButton OPCcrearDoc;
    private javax.swing.JButton OPCmyArea;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
