/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.Interfaces;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import proyecto2.FuncionesTEMP;
import static proyecto2.Interfaces.Vent_myArea.v3_1;
import proyecto2.ListaDocs;
import proyecto2.NodoDoc;

/**
 *
 * @author Samantha
 */
public class Vent_cancelar extends javax.swing.JFrame {
    public static Ventana3_1 v3_1;
    /**
     * Creates new form Vent_cancelar
     */
/**
 * Constructor para crear una nueva ventana Vent_cancelar.
 * Inicializa los componentes, establece la visibilidad de las ventanas,
 * llena el comboBox con los documentos en cola y establece el manejador del evento de cierre de la ventana.
 * @param v3_1 La ventana 3_1.
 */

    public Vent_cancelar(Ventana3_1 v3_1) {
        initComponents();
        this.v3_1= v3_1;
        v3_1.setVisible(false);
        this.setVisible(true);

        this.setLocationRelativeTo(null);
        
        ListaDocs Docs_User = Ventana1.ListaUsuarios.buscar_User(v3_1.getNombreUser()).getDocList();
        NodoDoc aux = Docs_User.getFirst();
        for (int i = 0; i < Docs_User.getSize(); i++) {
            if (aux.isColadeImpr()){
             DOCS_encola.addItem(aux.getNombreDoc());
            }
            aux= aux.getNext();
        }
        
          this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                FuncionesTEMP.WriteCSV(Ventana1.ListaUsuarios); ;
                
                System.exit(0);
            }
        });
        this.docs.setText(Ventana1.mont.mostrar(""));

          
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CerrarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DOCS_encola = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        DELETE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        docs = new javax.swing.JTextArea();
        DocSelected = new javax.swing.JTextField();
        atras = new javax.swing.JButton();
        CerrarSesion1 = new javax.swing.JButton();
        Colaventcancelarjlabel = new javax.swing.JLabel();
        FondoCancelar = new javax.swing.JLabel();

        CerrarSesion.setText("CERRAR SESIÓN");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sus documentos en la cola de impresión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        DOCS_encola.setBackground(new java.awt.Color(204, 204, 204));
        DOCS_encola.setForeground(new java.awt.Color(0, 0, 0));
        DOCS_encola.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DOCS_encolaItemStateChanged(evt);
            }
        });
        DOCS_encola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOCS_encolaActionPerformed(evt);
            }
        });
        jPanel1.add(DOCS_encola, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciones el documento que desea eliminar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        DELETE.setBackground(new java.awt.Color(204, 204, 204));
        DELETE.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        DELETE.setForeground(new java.awt.Color(0, 0, 0));
        DELETE.setText("Eliminar");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        docs.setBackground(new java.awt.Color(204, 204, 204));
        docs.setColumns(20);
        docs.setRows(5);
        jScrollPane1.setViewportView(docs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 190));

        DocSelected.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(DocSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        atras.setBackground(new java.awt.Color(204, 204, 204));
        atras.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        atras.setForeground(new java.awt.Color(0, 0, 0));
        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        CerrarSesion1.setBackground(new java.awt.Color(204, 204, 204));
        CerrarSesion1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        CerrarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        CerrarSesion1.setText("Cerrar sesión");
        CerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesion1ActionPerformed(evt);
            }
        });
        jPanel1.add(CerrarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        Colaventcancelarjlabel.setBackground(new java.awt.Color(255, 255, 255));
        Colaventcancelarjlabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Colaventcancelarjlabel.setForeground(new java.awt.Color(255, 255, 255));
        Colaventcancelarjlabel.setText("Cola de impresion");
        jPanel1.add(Colaventcancelarjlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        FondoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/FondoCancelar.png"))); // NOI18N
        jPanel1.add(FondoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 610, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método que se ejecuta cuando el estado del elemento seleccionado en DOCS_encola cambia.
 *@param evt El evento de cambio de estado del elemento seleccionado.
 */

    private void DOCS_encolaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DOCS_encolaItemStateChanged
        // TODO add your handling code here:
        String Dselected =(String) DOCS_encola.getSelectedItem();
        DocSelected.setText(Dselected);
    }//GEN-LAST:event_DOCS_encolaItemStateChanged

    private void DOCS_encolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOCS_encolaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DOCS_encolaActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón DELETE.
 * Elimina el documento seleccionado de la cola de impresión.
 * @param evt El evento de clic en el botón.
 */
    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
NodoDoc DocChoosed = Ventana1.ListaUsuarios.buscar_doc(v3_1.getNombreUser(),DocSelected.getText());
        DocChoosed.setColadeImpr(false);
        DocChoosed.setEtiquetaTiempo(0);
        Ventana1.mont.eliminar_doc(DocChoosed);
        String str = "";
        this.docs.setText(Ventana1.mont.mostrar(str));
    }//GEN-LAST:event_DELETEActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón 'atras'.
 * Hace que la ventana actual sea invisible y muestra la ventana v3_1.
 * @param evt El evento de clic en el botón.
 */
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v3_1.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v3_1.getV1().setVisible(true);
    }//GEN-LAST:event_CerrarSesionActionPerformed
/*
 Método que se ejecuta cuando se hace clic en el botón CerrarSesion.
 * Hace que la ventana actual sea invisible y muestra la ventana de inicio de sesión.
 * @param evt El evento de clic en el botón.
 */
    private void CerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesion1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v3_1.getV1().setVisible(true);
    }//GEN-LAST:event_CerrarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vent_cancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vent_cancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vent_cancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vent_cancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JButton CerrarSesion1;
    private javax.swing.JLabel Colaventcancelarjlabel;
    private javax.swing.JButton DELETE;
    private javax.swing.JComboBox<String> DOCS_encola;
    private javax.swing.JTextField DocSelected;
    private javax.swing.JLabel FondoCancelar;
    private javax.swing.JButton atras;
    private javax.swing.JTextArea docs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
