/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.Interfaces;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import proyecto2.FuncionesTEMP;
/**
 *
 * @author Alexandra padrón, Samantha Rojas
 */
public class Ventana2 extends javax.swing.JFrame {
    public static Ventana1 v1;

    private String tipo;
    
    /**
     * Creates new form Ventana2
     */
/**
 * Constructor para crear una nueva ventana Ventana2.
 * Inicializa los componentes, establece la visibilidad de las ventanas y establece el manejador del evento de cierre de la ventana.
 * @param v1 La ventana 1.
 */
    public Ventana2(Ventana1 v1) {

        this.tipo = "";
        
        initComponents();
        this.v1=v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
          this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                FuncionesTEMP.WriteCSV(v1.ListaUsuarios); //pilas
                
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        AtrásV2 = new javax.swing.JButton();
        SalirFV2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NewUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BAJA = new javax.swing.JCheckBox();
        Media = new javax.swing.JCheckBox();
        Alta = new javax.swing.JCheckBox();
        Registrar = new javax.swing.JButton();
        FondoV2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        AtrásV2.setBackground(new java.awt.Color(255, 255, 255));
        AtrásV2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        AtrásV2.setForeground(new java.awt.Color(0, 0, 0));
        AtrásV2.setText("Atrás");
        AtrásV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrásV2ActionPerformed(evt);
            }
        });
        getContentPane().add(AtrásV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        SalirFV2.setBackground(new java.awt.Color(204, 204, 204));
        SalirFV2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        SalirFV2.setForeground(new java.awt.Color(0, 0, 0));
        SalirFV2.setText("Salir");
        SalirFV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirFV2ActionPerformed(evt);
            }
        });
        getContentPane().add(SalirFV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese un nombre de usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        NewUser.setBackground(new java.awt.Color(204, 204, 204));
        NewUser.setForeground(new java.awt.Color(0, 0, 0));
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });
        getContentPane().add(NewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 160, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione el tipo de usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        BAJA.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BAJA.setText("Prioridad_Baja");
        BAJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAJAActionPerformed(evt);
            }
        });
        getContentPane().add(BAJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 30));

        Media.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Media.setText("Prioridad_Media");
        Media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediaActionPerformed(evt);
            }
        });
        getContentPane().add(Media, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        Alta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Alta.setText("Prioridad_Alta");
        Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaActionPerformed(evt);
            }
        });
        getContentPane().add(Alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        Registrar.setBackground(new java.awt.Color(204, 204, 204));
        Registrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Registrar.setForeground(new java.awt.Color(0, 0, 0));
        Registrar.setText("Crear usuario");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        FondoV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/FondoV2.png"))); // NOI18N
        getContentPane().add(FondoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método que se ejecuta cuando se hace clic en el botón 'AtrásV2'.
 * Hace que la ventana actual sea invisible y muestra la ventana v1.
 * @param evt El evento de clic en el botón.
 */
    private void AtrásV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrásV2ActionPerformed

        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_AtrásV2ActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón SalirFV2.
 * Escribe la lista de usuarios en un archivo CSV y cierra el programa.
 * @param evt El evento de clic en el botón.
 */
    private void SalirFV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirFV2ActionPerformed
        FuncionesTEMP.WriteCSV(Ventana1.ListaUsuarios);
        System.exit(0);
    }//GEN-LAST:event_SalirFV2ActionPerformed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
       
       
       
    }//GEN-LAST:event_NewUserActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón BAJA.
 * Establece el tipo de usuario a "prioridad_baja".
 * @param evt El evento de clic en el botón.
 */
    private void BAJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAJAActionPerformed
        // TODO add your handling code here:
        tipo = "prioridad_baja";
    }//GEN-LAST:event_BAJAActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón Media.
 * Establece el tipo de usuario a "prioridad_media".
 * @param evt El evento de clic en el botón.
 */
    private void MediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediaActionPerformed
        // TODO add your handling code here:
        tipo = "prioridad_media";
    }//GEN-LAST:event_MediaActionPerformed
/**
 * 
 * Método que se ejecuta cuando se hace clic en el botón Alta.
 * Establece el tipo de usuario a "prioridad_alta".
 * @param evt El evento de clic en el botón.
 */
    private void AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaActionPerformed
        // TODO add your handling code here:
        tipo = "prioridad_alta";
    }//GEN-LAST:event_AltaActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón Registrar.
 * Valida los datos ingresados y registra al usuario si son válidos.
 * @param evt El evento de clic en el botón.
 */
    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        String UserInput = "";
        UserInput= NewUser.getText();
        
        
        if (FuncionesTEMP.Validar(UserInput)  && !Ventana1.ListaUsuarios.containsHT(UserInput) && (Alta.isSelected() ^ BAJA.isSelected() ^ Media.isSelected() ) && !(Alta.isSelected() && BAJA.isSelected() && Media.isSelected()) ){
                    Ventana1.ListaUsuarios.insertar(UserInput, this.tipo);
                    JOptionPane.showMessageDialog(null, "BIENVENIDO "+UserInput + "!!!");
                    NewUser.setText("");
                    Alta.setSelected(false);
                    BAJA.setSelected(false);
                    Media.setSelected(false);
                    
            }
                    else{
                    if (Ventana1.ListaUsuarios.containsHT(UserInput)){
                        JOptionPane.showMessageDialog(null, "Nombre de Usuario no disponible.");
                    }  else if (!Alta.isSelected() ^ BAJA.isSelected() ^ Media.isSelected() || Alta.isSelected() && BAJA.isSelected() && Media.isSelected()){
                    JOptionPane.showMessageDialog(null, "Asegúrese de haber seleccionado solo un tipo de Usuario!");}
                    NewUser.setText("");
                    Alta.setSelected(false);
                    BAJA.setSelected(false);
                    Media.setSelected(false);
                    
            }
        
      
            
   
    }//GEN-LAST:event_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Alta;
    private javax.swing.JButton AtrásV2;
    private javax.swing.JCheckBox BAJA;
    private javax.swing.JLabel FondoV2;
    private javax.swing.JCheckBox Media;
    private javax.swing.JTextField NewUser;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton SalirFV2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
