/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.Interfaces;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import proyecto2.FuncionesTEMP;

/**
 *
 * @author alexp
 */
/**
 * /**
     * Constructor para crear una nueva ventana Ventana3.
     * Inicializa los componentes, establece la visibilidad de las ventanas y establece el manejador del evento de cierre de la ventana.
     *
     * @param v1 La ventana 1.
 * @author Alexandra Padrón y Samantha Rojas
 */
/**
Constructor para crear una nueva ventana Ventana3.
Inicializa los componentes, establece la visibilidad de las ventanas y establece el manejador del evento de cierre de la ventana.
 @param v1 La ventana 1.
 */
public class Ventana3 extends javax.swing.JFrame {
    public static Ventana1 v1;
    /**
     * Creates new form Ventana3
     */
    public Ventana3(Ventana1 v1) {
        initComponents();
        this.v1=v1;
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
         this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                FuncionesTEMP.WriteCSV(v1.ListaUsuarios); 
                
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atrasv3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inicioUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        FondoV2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        Atrasv3.setBackground(new java.awt.Color(204, 204, 204));
        Atrasv3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Atrasv3.setForeground(new java.awt.Color(0, 0, 0));
        Atrasv3.setText("Atrás");
        Atrasv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atrasv3ActionPerformed(evt);
            }
        });
        getContentPane().add(Atrasv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 30));

        inicioUsuario.setBackground(new java.awt.Color(204, 204, 204));
        inicioUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        inicioUsuario.setForeground(new java.awt.Color(0, 0, 0));
        inicioUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(inicioUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Para iniciar sesión escriba su nombre de usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        ok.setBackground(new java.awt.Color(204, 204, 204));
        ok.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ok.setForeground(new java.awt.Color(0, 0, 0));
        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        FondoV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/FondoCancelar.png"))); // NOI18N
        getContentPane().add(FondoV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 *  Método que se ejecuta cuando se hace clic en el botón 'Atrasv3'.
 * Hace que la ventana actual sea invisible y muestra la ventana v1.
 * @param evt El evento de clic en el botón.
 */
    private void Atrasv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atrasv3ActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_Atrasv3ActionPerformed

    private void inicioUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioUsuarioActionPerformed
       
    }//GEN-LAST:event_inicioUsuarioActionPerformed
/**
 * Método que se ejecuta cuando se hace clic en el botón 'ok'.
 * Valida el nombre de usuario ingresado y muestra un mensaje de bienvenida si el usuario existe.
 * Si el usuario no existe, muestra un mensaje de error.
 * @param evt El evento de clic en el botón.

 */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String UserInput = "";
        UserInput= inicioUsuario.getText();
        if (v1.ListaUsuarios.containsHT(UserInput)){
            JOptionPane.showMessageDialog(null, "Hola " + UserInput + " bienvenido de nuevo!");
            //Ventana1.timer.pausar();                                                                                                                                        //estas 3 lineas no,solo mientras
            //JOptionPane.showMessageDialog(null,Ventana1.timer.getSegundos()); // eSTO ES UN EJEMPLO
            //Ventana1.timer.reanudar();                                                                                                                     //  PARA ESTABLECER ETIQUETA DE TIEMPO, ESTO NO VA AQUI ES MIENTRAS
            inicioUsuario.setText("");                                                                                                                     
            this.setVisible(false);
            Ventana3_1 ventana3_1= new Ventana3_1 (v1,UserInput);
            
            ventana3_1.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario No encontrado!. Asegúrese de haberse registrado.");
            inicioUsuario.setText("");
        }
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atrasv3;
    private javax.swing.JLabel FondoV2;
    private javax.swing.JTextField inicioUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
